apiVersion: v1
clusters:
- cluster:
    certificate-authority: 
    server: 
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    as-user-extra: {}
    client-certificate: /root/.kube/client.crt
    client-key: /root/.kube/client.key